export const USER_EMAILJS_SERVICE_ID =
  process.env.NEXT_PUBLIC_USER_EMAILJS_SERVICE_ID;
export const USER_EMAILJS_TEMPLATE_ID =
  process.env.NEXT_PUBLIC_USER_EMAILJS_TEMPLATE_ID;
export const USER_EMAILJS_PUBLIC_KEY =
  process.env.NEXT_PUBLIC_USER_EMAILJS_PUBLIC_KEY;

// manager
export const MANAGER_EMAILJS_SERVICE_ID =
  process.env.NEXT_PUBLIC_MANAGER_EMAILJS_SERVICE_ID;
export const MANAGER_EMAILJS_TEMPLATE_ID =
  process.env.NEXT_PUBLIC_MANAGER_EMAILJS_TEMPLATE_ID;
export const MANAGER_EMAILJS_PUBLIC_KEY =
  process.env.NEXT_PUBLIC_MANAGER_EMAILJS_PUBLIC_KEY;
