export const USER_EMAILJS_SERVICE_ID =
  process.env.USER_EMAILJS_SERVICE_ID;
export const USER_EMAILJS_TEMPLATE_ID =
  process.env.USER_EMAILJS_TEMPLATE_ID;
export const USER_EMAILJS_PUBLIC_KEY =
  process.env.USER_EMAILJS_PUBLIC_KEY;
